[wokwi]
version = 1
gdbServerPort = 3333
elf = "../ESP32_GENERIC_C3-20240602-v1.23.0.bin"
firmware = "../ESP32_GENERIC_C3-20240602-v1.23.0.bin"
rfc2217ServerPort = 4000

[[chip]]
name = "dht20"
binary = "chips/dht20.chip.wasm"