[wokwi]
version = 1
gdbServerPort = 3333
elf = "../target/riscv32imc-unknown-none-elf/debug/esp32-c3-devkitc-02-rust-bm"
firmware = "../target/riscv32imc-unknown-none-elf/debug/esp32-c3-devkitc-02-rust-bm"

[[chip]]
name = "dht20"
binary = "chips/dht20.chip.wasm"