name: MicroPython ESP32 CI Test

on: 
  push:
    paths:
    - 'micropython_esp32/**'
    - '.github/workflows/micropython_esp32.yml'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11
      - name: Install dependencies
        working-directory: micropython_esp32
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Test with pytest
        working-directory: micropython_esp32
        run: pytest
